//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezerwacje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rezerwacje()
        {
            this.Uslugi = new HashSet<Uslugi>();
        }
    
        public int IdRezerwacji { get; set; }
        public Nullable<System.DateTime> DataRozpoczecia { get; set; }
        public Nullable<System.DateTime> DataZakonczenia { get; set; }
        public Nullable<int> IdPokoju { get; set; }
        public Nullable<decimal> Netto { get; set; }
        public Nullable<double> Rabat { get; set; }
        public Nullable<double> VAT { get; set; }
        public Nullable<decimal> Brutto { get; set; }
        public Nullable<decimal> DoZaplaty { get; set; }
    
        public virtual Pokoje Pokoje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Uslugi> Uslugi { get; set; }
    }
}
