//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class StanowiskaPracownikow
    {
        public int IdStanowiskaPracownika { get; set; }
        public Nullable<int> IdPracownika { get; set; }
        public Nullable<System.DateTime> DataOd { get; set; }
        public Nullable<System.DateTime> DataDo { get; set; }
        public Nullable<int> IdStanowiska { get; set; }
    
        public virtual Pracownicy Pracownicy { get; set; }
        public virtual Stanowiska Stanowiska { get; set; }
    }
}
